/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sprites;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Duran
 */
public class FrmSprite extends javax.swing.JFrame {
//int contador = 0;
ClsAnimacion animar;
    /**
     * Creates new form FrmSprite
     */
    public FrmSprite() {
        initComponents();
        animar = new ClsAnimacion(jpanimar.getSize());
        animar.setvelocidad(60);
        jpanimar.add(animar);
        jpanimar.repaint();
        /*String path = "m1.PNG";  
        URL url = this.getClass().getResource(path);  
        ImageIcon icon = new ImageIcon(url);  
        lbldibujo.setIcon(icon);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldibujo = new javax.swing.JLabel();
        btnanimar = new javax.swing.JButton();
        jpanimar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnanimar.setText("Animar");
        btnanimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanimarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanimarLayout = new javax.swing.GroupLayout(jpanimar);
        jpanimar.setLayout(jpanimarLayout);
        jpanimarLayout.setHorizontalGroup(
            jpanimarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jpanimarLayout.setVerticalGroup(
            jpanimarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbldibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jpanimar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnanimar)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpanimar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnanimar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnanimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanimarActionPerformed
        // TODO add your handling code here:
        
        animar.startAnimation();
//        esperar(2000);
//        animar.stopAnimation();
        
        
        
        
        
        
        
        
        /*
        System.out.println("sentencia 1");

        try {
            Thread.sleep (10000);
        } catch (Exception e) {
        // Mensaje en caso de que falle
        }

        System.out.println("sentencia 2");
        */
        
        
        //String path = "mario.gif";
        /*if (contador == 0){
            path = "Mario1.JPG";
        }else{
            path = "Mario2.JPG";
        }*/
        
        /*
        URL url = this.getClass().getResource(path);  
        ImageIcon icon = new ImageIcon(url);  
  
        lbldibujo.setIcon(icon);
        contador++;
        if(contador > 1){
            contador = 0;
        }
        */
        
        /*
       int i = 1;
        try {
            dibujar("m1.PNG");
            Object obj = new Object();
         synchronized (obj) {
            obj.wait(1000);
            dibujar("m2.PNG");
            i++;
            lbldibujo.setText(""+i);
            obj.wait(1000);
            dibujar("m3.PNG");
            i++;
            lbldibujo.setText(""+i);
            obj.wait(1000);
            dibujar("m4.PNG");
            i++;
            lbldibujo.setText(""+i);
            obj.wait(1000);
            dibujar("m5.PNG");
            i++;
            lbldibujo.setText(""+i);
     }
            
            
        } catch (Exception e) {
        // Mensaje en caso de que falle
        }
        
        
        
        /*for(int i = 1 ; i <= 12 ; i++){
            path = "m"+i+".PNG";
            URL url = this.getClass().getResource(path);  
            ImageIcon icon = new ImageIcon(url);  
            lbldibujo.setIcon(icon);
            esperar(1);
        }*/
    }//GEN-LAST:event_btnanimarActionPerformed
    
    public void dibujar(String path){
            //path = "m"+i+".PNG";
            URL url = this.getClass().getResource(path);  
            ImageIcon icon = new ImageIcon(url);  
            lbldibujo.setIcon(icon);

    }
    
    public void esperar (int segundos) {
        try {
            Thread.sleep (segundos*1000);
        } catch (Exception e) {
    // Mensaje en caso de que falle
            System.out.println("fallo");
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSprite().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanimar;
    private javax.swing.JPanel jpanimar;
    private javax.swing.JLabel lbldibujo;
    // End of variables declaration//GEN-END:variables
}
